#include <driver/gpio.h>

#ifdef CONFIG_IDF_TARGET_ESP32C2
#define APP_REMOTE_CTRL_BTN_GPIO      GPIO_NUM_9
#elif CONFIG_IDF_TARGET_ESP32C3
#define APP_REMOTE_CTRL_BTN_GPIO      GPIO_NUM_9
#elif CONFIG_IDF_TARGET_ESP32
#define APP_REMOTE_CTRL_BTN_GPIO      GPIO_NUM_0
#elif CONFIG_IDF_TARGET_ESP32S2
#define APP_REMOTE_CTRL_BTN_GPIO      GPIO_NUM_0
#elif CONFIG_IDF_TARGET_ESP32S3
#define APP_REMOTE_CTRL_BTN_GPIO      GPIO_NUM_0
#elif CONFIG_IDF_TARGET_ESP32C6
#define APP_REMOTE_CTRL_BTN_GPIO      GPIO_NUM_9
#endif
